# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: DotNet Test

on:
  workflow_call:
  inputs:
    solution:
      description: 'The solution file to build'
      default: '**/*.sln'
      required: true
    dotnet-version:
      description: 'The .NET version to use'
      default: '9.0.x'
      required: true
    configuration:
      description: 'The build configuration to use'
      default: 'Debug'
      required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore ${{ inputs.solution }}

      - name: Build
        run: dotnet build --no-restore --configuration ${{ inputs.configuration }} ${{ inputs.solution }}

      - name: Unit Tests
        run: dotnet test --no-build --verbosity normal
